# Generated by Django 3.0.8 on 2020-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
